### ISSUE TITLE
Nice!

### ISSUE THREAD

**Issue by djaiss** [bencaron/dotfiles#1]
Tu crées ton dotfiles au final :-)

**Comment by bencaron** [comment]
Ban, je vie entre 2 ordinateurs maintenant.. :)

J'ai sans surprise PLEIN de choses à ajuster sous Lion...

On Mon, May 14, 2012 at 2:55 PM, djaiss <
reply@reply.github.com

**Comment by bencaron** [comment]
Drole de te voir fermer ça, vu que je gères ça avec cider maintenant :D

**Comment by djaiss** [comment]
Il me restait quelques issues ouvertes depuis longtemps et ca me gossait :-)

**Comment by djaiss** [comment]
Fini Vim alors?

**Comment by bencaron** [comment]
Vim pour les petits changements vite fait dans le terminal, Atom pour les grosses jobs pleins écrans.

Avec vim-mode bien sur!

Y'a du bon progrès, mais je m'ennuie de faire un :0,$:s/patate/pouelle/

Et on devrait luncher ensemble plutôt que de se parler via un vieux issue ;)
